# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46dd0cfed48d018d8e46c7c60aa53761e217f6f7e1f71cc2633491d30d9788f3e22daa3d68af0b9224ffeb3690adfe162e90d2851cd5a25c1361690fa0c8c053

test:
  secret_key_base: f538dd9afc8b118c87b39b9ce2c1335579054ba54e89260509a11f6cf1d1868efd461726f0f81e653507a762523a8b021b9d67f8c730bd56a75a8d7ef38e6512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
